### ISSUE TITLE
Questions about performance

### ISSUE THREAD

**Issue by Renp1ngs** [xiaoachen98/DDB#6]
Dear Lin Chen:
In Table1 (b). 
> +CutMix = 54.9
> +ClassMix = 54.3

But in Tabel 6 
> RegionPath(CutMix) = 55.5
> ClassPath(ClassMix) = 55.0 

So:
1. Which set of results is the real result of cross-domain CutMix and cross-domain ClassMix?
2. And for corss-domain ClassMix, the DACS result is 52.14, why is every one of your results higher than this? 
3. And why are there two different source-only results in multiple tables?

Looking forward to your reply.

**Comment by Renp1ngs** [comment]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/40795237/193796195-b29de3f0-8c5d-45a2-a4ff-c95e3ee0d55e.png">

The batch size of dacs is also equal to 2, and in Tabel3 of DACS, the cross-domain CutMix is only 48.69, so how do you achieve your improvement?

**Comment by xiaoachen98** [comment]
> 

Thanks for your interest and attention. 
1. All results reported in the paper are real and conducted several times. As shown in Table 1, multiple experiments conducted under the same experimental setup may also yield experimental results that fluctuate within a specific range. We have released the code and you can run it several times to verify the results.
2. The main difference lies in that we leveraged the common AdamW optimizer and learning rate warm-up strategy. By the way, we drop the GaussianBlur augmentation.
3. Because the experiment settings are different among the tables. We conducted experiments on single-source, multiple-source, and multiple-target domain settings.

**Comment by Renp1ngs** [comment]
So which set of results should I cite as the result of classmix and cutmix alone with batch size equal to 2?

**Comment by xiaoachen98** [comment]
> So which set of results should I cite as the result of classmix and cutmix alone with batch size equal to 2?

You can choose the average results reported in Table 1.

**Comment by Renp1ngs** [comment]
> The main difference lies in that we leveraged the common AdamW optimizer and learning rate warm-up strategy. By the way, we drop the GaussianBlur augmentation.

RCS and FD in DAFormer wasn't used in your results?

**Comment by xiaoachen98** [comment]
> > The main difference lies in that we leveraged the common AdamW optimizer and learning rate warm-up strategy. By the way, we drop the GaussianBlur augmentation.
> 
> RCS and FD in DAFormer wasn't used in your results?

We didn't use RCS and FD techniques.

**Comment by Renp1ngs** [comment]
But you have this technique in your code, so do you have the results of cutmix and classmix alone after using RCS ,FD and learning rate warm-up ?

**Comment by xiaoachen98** [comment]
> But you have this technique in your code, so do you have the results of cutmix and classmix alone after using RCS ,FD and learning rate warm-up ?

Our code is built on their code base. Although the codes related to RCS and FD technologies are not removed, we didn't use them. And you can run the experiment you cared for by modifying the config file.

**Comment by Renp1ngs** [comment]
Thanks for your reply.
